name: Docker Image CI for jupyter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd jupyter
        mkdir jupyter
        cp requirements.txt jupyter
        docker build . --tag pnavaro/jupyter:latest
